namespace: lmw-fitness
env: production
allowedOrigin: https://www.lmwfitness.co.uk
replicaCount: 1
image:
  pullPolicy: Always
storage:
  storageClass: standard
webserver:
  image:
    repository: index.docker.io/lmwcode/lmw-fitness-frontend:9ce5fca8341367071dc3f6d2d0029fae08948524
  port: 5052
  type: NodePort
  host: www.lmwfitness.co.uk
  path: /
  pathType: Prefix
  recaptcha: 6Ldn3-0qAAAAAMWv4iekZdMl4Xrfj2Av2zEL7onD
  backendUrl: "https://api.lmwfitness.co.uk"
  applicationType: frontend
api:
  host: api.lmwfitness.co.uk
  port: 8082
  path: /api/
  pathType: Prefix
  applicationType: backend
# backendServiceHost: lmwfitness-backend-service # Blue frontend (k get svc lmwfitness-frontend-service -n lmw-fitness -o yaml. Selector = colour)
backendServiceHost: lmwfitness-backend-service-stage # Green frontend
livenessProbe:
  endpoint: /api/health/live
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /api/health/ready
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
