namespace: lmw-fitness
env: production
allowedOrigin: https://www.lmwfitness.co.uk
allowCredentials: false
frontend_url: https://www.lmwfitness.co.uk
replicaCount: 1
platform: linux/amd64
image:
  pullPolicy: Always
storage:
  storageClass: standard
api:
  image:
    repository: index.docker.io/lmwcode/lmw-fitness-backend
    tag: v.<+pipeline.sequenceId>
  host: api.lmwfitness.co.uk
  port: 8082
  path: /api/
  type: NodePort
  protocol: TCP
  pathType: Prefix
  applicationType: backend
images:
  directory: images
database:
  name: LMWfitness
  user: postgres
  port: 5432
  type: ClusterIP
  protocol: TCP
  sslMode: disable
webserver:
  host: www.lmwfitness.co.uk
smtp:
  host: smtp.ionos.co.uk
  port: 587
  username: info@lmwfitness.co.uk
  from: info@lmwfitness.co.uk
  to: info@lmwfitness.co.uk
brevo:
  apiURL: https://api.brevo.com/v3
  newsletter:
    listID: 15
    DOItemplateID: 2
    DOIRedirectURL: https://www.lmwfitness.co.uk/newsletter/confirm
  lists:
    mindset: 17
    beginner: 10
    advanced: 12
    tailoredCoaching: 14
  templates:
    mindsetPackage: 8
    beginnerProgram: 6
    advancedProgram: 7
    tailoredCoaching: 9
    orderConfirmation: 10
admin:
  email: info@lmwfitness.co.uk
seedUser:
  email: warren_laura@yahoo.co.uk
livenessProbe:
  endpoint: /api/health/live
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /api/health/ready
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
