namespace: lmw-fitness
env: production
allowedOrigin: https://www.lmwfitness.co.uk
replicaCount: 1
image:
  pullPolicy: Always
storage:
  storageClass: standard
api:
  image:
    repository: index.docker.io/lmwcode/lmw-fitness-backend:424a282b6c40202eb268a5310f998ac9506ced74
  host: api.lmwfitness.co.uk
  port: 8082
  path: /api/
  type: NodePort
  nodePort: 30260
  pathType: Prefix
images:
  directory: images
database:
  name: LMWfitness
  user: postgres
  port: 5432
  type: ClusterIP
  sslMode: disable
smtp:
  host: smtp.ionos.co.uk
  port: 587
  username: info@lmwfitness.co.uk
  from: info@lmwfitness.co.uk
  to: info@lmwfitness.co.uk
livenessProbe:
  endpoint: /api/health/live
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /api/health/ready
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
