apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.lmwfitness.co.uk"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
      - {{ .Values.api.host }}
      secretName: lmwfitness-ssl
  rules:
  - host: {{ .Values.api.host }}
    http:
      paths:
      - path: {{ .Values.api.path }}
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: {{ .Values.namespace }}-backend-service
            port:
              number: {{ .Values.api.port }}
      - path: /debug/images
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: {{ .Values.namespace }}-backend-service
            port:
              number: {{ .Values.api.port }}
      - path: /images
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: {{ .Values.namespace }}-backend-service
            port:
              number: {{ .Values.api.port }}