apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: lmw-fitness
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: lmw-fitness
subjects:
- kind: ServiceAccount
  name: default
  namespace: lmw-fitness
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io