apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Values.namespace }}-backend-service
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
    app.kubernetes.io/instance: lmw-fitness-backend
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    nodePort: {{ .Values.api.nodePort }}
  type: {{ .Values.api.type }}
  