apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lmwfitness-frontend-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmwfitness-frontend-ingress
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-certificate: lmwfitness-ssl
spec:
  ingressClassName: nginx
  tls: 
    - hosts:
      - {{ .Values.webserver.host | quote }}
      - {{ .Values.api.host | quote }}
      secretName: lmwfitness-ssl
  rules:
  - host: {{ .Values.webserver.host | quote }}
    http:
      paths:
      - path: {{ .Values.webserver.path }}
        pathType: {{ .Values.webserver.pathType }}
        backend:
          service:
            name: lmwfitness-frontend-service
            port:
              number: {{ .Values.webserver.port }}
  - host: {{ .Values.api.host | quote }}
    http:
      paths:
      - path: {{ .Values.api.path }}
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: lmw-fitness-api-service
            port:
              number: {{ .Values.api.port }}
      - path: /debug/images/
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: lmw-fitness-api-service
            port:
              number: {{ .Values.api.port }}
      - path: /images/
        pathType: {{ .Values.api.pathType }}
        backend:
          service:
            name: lmw-fitness-api-service
            port:
              number: {{ .Values.api.port }}
     