apiVersion: v1
kind: Service
metadata:
  name: lmwfitness-frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmwfitness-frontend-service
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
    app.kubernetes.io/instance: lmwfitness-frontend
  type: {{ .Values.webserver.type }}
  ports:
  - port: {{ .Values.webserver.port }}
    targetPort: {{ .Values.webserver.port }}