apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  GO_ENV: "{{ .Values.env }}"
  ALLOWED_ORIGIN: "{{ .Values.allowedOrigin }}"
  ALLOW_CREDENTIALS: "{{ .Values.allowCredentials }}"
  FRONTEND_URL: "{{ .Values.frontend_url }}"
  PORT: "{{ .Values.api.port }}"
  DB_HOST: "{{ .Release.Name }}-postgres-service"
  DB_USER: "{{ .Values.database.user }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_SSLMODE: "{{ .Values.database.sslMode }}"
  STORAGE_CLASS: "{{ .Values.storage.storageClass }}"
  SMTP_HOST: "{{ .Values.smtp.host }}"
  SMTP_PORT: "{{ .Values.smtp.port }}"
  SMTP_USERNAME: "{{ .Values.smtp.username }}"
  SMTP_FROM: "{{ .Values.smtp.from }}"
  SMTP_TO: "{{ .Values.smtp.to }}"
  PLATFORM: "{{ .Values.platform }}"
  SECRET_NAME: "{{ .Values.api.secretName }}"
  BREVO_API_URL: "{{ .Values.brevo.apiURL }}"
  NEWSLETTER_BREVO_LIST_ID: "{{ .Values.brevo.newsletter.listID }}"
  BREVO_NEWSLETTER_DOI_TEMPLATE_ID: "{{ .Values.brevo.newsletter.DOItemplateID }}"
  BREVO_DOI_REDIRECT_URL: "{{ .Values.brevo.newsletter.DOIRedirectURL }}"
  BREVO_BEGINNER_LIST_ID: "{{ .Values.brevo.payments.beginnerListID }}"
  BREVO_ADVANCED_LIST_ID=: "{{ .Values.brevo.payments.advancedListID }}"
  BREVO_MINDSET_PACKAGE_TEMPLATE_ID: "{{ .Values.brevo.payments.minsetPackageListID }}"
  BREVO_TAILORED_COACHING_TEMPLATE_ID: "{{ .Values.brevo.payments.tailoredListID }}"
