apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webserver.applicationType }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.api.applicationType }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}-deployment
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.applicationType }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.applicationType }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: 
        - "sh"
        - "-c"
        - "until nc -z {{ .Release.Name }}-postgres-service.{{ .Values.namespace }}.svc.cluster.local 5432; do echo waiting for postgres; sleep 20; done;"
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
      containers:
      - name: debug-shell
        image: nicolaka/netshoot
        command: 
        - sh
        - -c
        - |
          apk add --no-cache postgresql-client && sleep 3600
        stdin: true
        tty: true
      - name: {{ .Values.api.applicationType }}
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.api.port }}
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DB_PASSWORD
        - name: SMTP_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: SMTP_PASSWORD
        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: RECAPTCHA_SECRET
        - name: ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ACCESS_SECRET_KEY
        - name: REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: REFRESH_SECRET_KEY
        - name: BREVO_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: BREVO_API_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: BEGINNER_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: BEGINNER_PRICE_ID
        - name: ADVANCED_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ADVANCED_PRICE_ID
        - name: TAILORED_COACHING_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: TAILORED_COACHING_PRICE_ID
        - name: ULTIMATE_MINDSET_PACKAGE_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ULTIMATE_MINDSET_PACKAGE_PRICE_ID
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ADMIN_PASSWORD
        - name: SEED_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: SEED_USER_PASSWORD
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.endpoint }}
            port: {{ .Values.api.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.endpoint }}
            port: {{ .Values.api.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
        startupProbe:
          httpGet:
            path: {{ .Values.readinessProbe.endpoint }}
            port: {{ .Values.api.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5