apiVersion: v1
kind: Service
metadata:
  name: lmwfitness-backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmwfitness-backend-service
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
    app.kubernetes.io/instance: lmwfitness-backend
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
    protocol: TCP
    nodePort: {{ .Values.api.nodePort }}
  type: {{ .Values.api.type }}
  